name: "Install dependencies"
description: "Prepare nodejs and all dependencies"

inputs:
  node-version:
    description: "Node.js version to use"
    default: "22"
  setup-node:
    description: "Setup Node.js environment"
    default: true
    required: false
  audit:
    description: "Run npm audit after installation"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup nodejs
      if: ${{ inputs.setup-node == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      run: npm ci --ignore-scripts --audit=false
      shell: bash

    - name: Run npm audit
      if: ${{ inputs.audit == 'true' }}
      run: npm audit --audit-level=high --omit=dev
      shell: bash
