export const tokens = {
  radius: {
    sm: "0.375rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    pill: "9999px",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
  },
  color: {
    bg: "var(--color-bg)",
    fg: "var(--color-fg)",
    muted: "var(--color-muted)",
    border: "var(--color-border)",
    primary: "var(--color-primary)",
    primaryFg: "var(--color-primary-fg)",
    accent: "var(--color-accent)",
    accentFg: "var(--color-accent-fg)",
    success: "var(--color-success)",
    warning: "var(--color-warning)",
    danger: "var(--color-danger)",
  },
};
