export const enum SdkErrorCode {
  CONFIG_ERROR = "CONFIG_ERROR",
  ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
  WALLET_REQUIRED = "WALLET_REQUIRED",
  CHAIN_MISMATCH = "CHAIN_MISMATCH",

  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_ADDRESS = "INVALID_ADDRESS",

  RPC_ERROR = "RPC_ERROR",
  RATE_LIMITED = "RATE_LIMITED",
  NETWORK_ERROR = "NETWORK_ERROR",

  CONTRACT_REVERT = "CONTRACT_REVERT",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  USER_REJECTED = "USER_REJECTED",

  UNKNOWN = "UNKNOWN",
}
