export enum SdkErrorCode {
  ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
  INVALID_ADDRESS = "INVALID_ADDRESS",

  WALLET_REQUIRED = "WALLET_REQUIRED",

  USER_REJECTED = "USER_REJECTED",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",

  SIMULATION_REVERTED = "SIMULATION_REVERTED",
  CONTRACT_REVERTED = "CONTRACT_REVERTED",

  NETWORK_ERROR = "NETWORK_ERROR",
  RPC_ERROR = "RPC_ERROR",

  UNKNOWN = "UNKNOWN",
  ABORTED = "ABORTED",
}
