export enum SdkErrorCode {
  ABI_ITEM_NOT_FOUND = "ABI_ITEM_NOT_FOUND",
  ABORTED = "ABORTED",

  ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",

  CONTRACT_REVERTED = "CONTRACT_REVERTED",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",

  INVALID_ADDRESS = "INVALID_ADDRESS",
  NETWORK_ERROR = "NETWORK_ERROR",

  RPC_ERROR = "RPC_ERROR",
  SIMULATION_REVERTED = "SIMULATION_REVERTED",

  UNKNOWN = "UNKNOWN",
  USER_REJECTED = "USER_REJECTED",

  WALLET_REQUIRED = "WALLET_REQUIRED",
}
