name: "Lint"
description: "Lints the code in the repo"

inputs:
  check-changesets:
    description: "Whether to check for pending changesets"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate config
      working-directory: ./config
      run: npm run check
      shell: bash

    - name: Lint
      run: npm run lint -- --debug
      shell: bash

    - name: Check code formatting
      run: npm run check:format
      shell: bash

    # - name: Check for unused files, dependencies, and exports
    #   run: npm run knip
    #   shell: bash

    - name: Check that only allowed licenses are used in production
      run: npm run check:licenses
      shell: bash

    - name: Check dependency versions with Syncpack
      run: npm run check:syncpack
      shell: bash

    - name: Check that workspace packages use current versions
      run: npm run check:packages-sync
      shell: bash

    - name: Fetch base branch
      if: ${{ inputs.check-changesets == 'true' }}
      shell: bash
      run: git fetch origin ${{ github.base_ref }} --depth=1

    - name: Check for pending Changesets
      id: changesets
      if: ${{ inputs.check-changesets == 'true' }}
      run: npm run check:changesets -- --since=origin/${{ github.base_ref }}
      shell: bash
      continue-on-error: true

    - name: Changesets warning
      if: ${{ steps.changesets.outcome == 'failure' }}
      run: |
        echo "::warning title=Changesets::Packages changed but no changesets found. Run 'npm run changeset:add' (or 'changeset add --empty' if no release needed)."
        echo "### Changesets" >> $GITHUB_STEP_SUMMARY
        echo "Packages changed but no changesets found." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Run \`npm run changeset:add\` (or \`changeset add --empty\`)." >> $GITHUB_STEP_SUMMARY
      shell: bash
