name: "Lint"
description: "Lints the code in the repo"

runs:
  using: "composite"
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Check code formatting
      run: npm run check:format
      shell: bash

    # - name: Check for unused files, dependencies, and exports
    #   run: npm run knip
    #   shell: bash

    - name: Check that only allowed licenses are used in production
      run: npm run check:licenses
      shell: bash

    - name: Check that prod dependencies are pinned to specific versions
      run: npm run check:deps-pinning
      shell: bash
